// <auto-generated />
using BarCreate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarCreate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250912103726_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarCreate.Models.Barkod", b =>
                {
                    b.Property<string>("BarkodNo")
                        .HasColumnType("char(10)");

                    b.Property<decimal>("EksiltmeMiktar")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("KasaIciMiktar")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("StokNo")
                        .IsRequired()
                        .HasColumnType("char(18)");

                    b.HasKey("BarkodNo");

                    b.HasIndex("StokNo");

                    b.ToTable("Barkod", (string)null);
                });

            modelBuilder.Entity("BarCreate.Models.StokKartBilgi", b =>
                {
                    b.Property<string>("StokNo")
                        .HasColumnType("char(18)");

                    b.Property<decimal>("EksiltmeMiktar")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("KasaIciMiktar")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("StokNo");

                    b.ToTable("StokKartBilgi", (string)null);
                });

            modelBuilder.Entity("BarCreate.Models.Barkod", b =>
                {
                    b.HasOne("BarCreate.Models.StokKartBilgi", "Stok")
                        .WithMany("Barkodlar")
                        .HasForeignKey("StokNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("BarCreate.Models.StokKartBilgi", b =>
                {
                    b.Navigation("Barkodlar");
                });
#pragma warning restore 612, 618
        }
    }
}
